### ISSUE TITLE
BUG: Cleanup reports doesn't work

### ISSUE THREAD

**Issue by mstankovic** [CyborgTests/playwright-reports-server#63]
I still have reports older then X days..
P.S. Results are properly cleaned! 
Searching through logs i found out that no "console.log(`[cron-job] found ${outdated.length} outdated reports`);" line logged. 

When I filter logs, I can see: 

```
[cron-job] starting outdated reports lookup...
[cron-job] starting outdated results lookup...
[cron-job] found 4 outdated results
[cron-job] starting outdated reports lookup...
[cron-job] starting outdated results lookup...
[cron-job] found 4 outdated results
[cron-job] starting outdated reports lookup...
[cron-job] starting outdated results lookup...
[cron-job] found 4 outdated results
[cron-job] starting outdated reports lookup...
[cron-job] starting outdated results lookup...
[cron-job] found 12 outdated results
[cron-job] starting outdated reports lookup...
[cron-job] starting outdated results lookup...
[cron-job] found 4 outdated results
[cron-job] starting outdated reports lookup...
[cron-job] starting outdated results lookup...
[cron-job] found 4 outdated results
[cron-job] starting outdated reports lookup...
[cron-job] starting outdated results lookup...
[cron-job] found 4 outdated results
[cron-job] starting outdated results lookup...
[cron-job] starting outdated reports lookup...
[cron-job] found 4 outdated results
[cron-job] starting outdated results lookup...
[cron-job] starting outdated reports lookup...
[cron-job] found 4 outdated results
[cron-job] starting outdated reports lookup...
[cron-job] starting outdated results lookup...
[cron-job] found 8 outdated results
[cron-job] starting outdated reports lookup...
[cron-job] starting outdated results lookup...
[cron-job] found 8 outdated results
[cron-job] starting outdated reports lookup...
[cron-job] starting outdated results lookup...
[cron-job] found 8 outdated results
```

Configuration is added via env:

```
environment:
      RESULT_EXPIRE_DAYS: 20
      RESULT_EXPIRE_CRON_SCHEDULE: "0 15 * * *" #every day at 15h
      REPORT_EXPIRE_DAYS: 20
      REPORT_EXPIRE_CRON_SCHEDULE: "0 15 * * *" #every day at 15h
```

**Comment by milos-stankovic-allhuman** [comment]
Hi @soloviovmax 

```
services:
  playwright-reports-server:
    image: ghcr.io/cyborgtests/playwright-reports-server:4.2.0
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - playwright-data:/playwright-data
    networks:
      - nginx-proxy
    environment:
      RESULT_EXPIRE_DAYS: 20
      RESULT_EXPIRE_CRON_SCHEDULE: "0 15 * * *" #every day at 15h
      REPORT_EXPIRE_DAYS: 20
      REPORT_EXPIRE_CRON_SCHEDULE: "0 15 * * *" #every day at 15h
      VIRTUAL_HOST: playwright-reports.mydomain.rs
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: playwright-reports.mydomain.rs

volumes:
  playwright-data:

networks:
  nginx-proxy:
    external: true
```
Cannot update to the latest version since there is a bug where I cannot generate report..
